# Generated by Django 3.2.8 on 2021-11-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_comment_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
